import pytest
import logging
from unittest.mock import AsyncMock, MagicMock, patch

from app.schemas.arena import AgentDecision
from app.providers.base import BaseLLMProvider, LLMProviderError
from app.providers.gemini_provider import GeminiProvider
from app.providers.openai_compatible import GroqProvider, OpenRouterProvider, OpenAICompatibleProvider
from app.providers.fallback_provider import FallbackRuleProvider, SecondaryLLMProvider
from app.providers.manager import LLMProviderManager
from app.orchestration.graph_nodes import LangGraphNegotiationEngine, NegotiationState
from app.core.config import settings


class MockFailingProvider(BaseLLMProvider):
    def __init__(self, name: str, is_quota: bool = False, is_transient: bool = True):
        self._name = name
        self.is_quota = is_quota
        self.is_transient = is_transient
        self.call_count = 0

    def provider_name(self) -> str:
        return self._name

    def supports_structured_output(self) -> bool:
        return True

    async def health_check(self) -> bool:
        return True

    async def generate_decision(
        self, prompt: str, agent_personality: str, agent_role: str, current_round: int, scenario_id: str, *args, **kwargs
    ) -> AgentDecision:
        self.call_count += 1
        raise LLMProviderError(
            message=f"Simulated failure for {self._name}",
            provider_name=self._name,
            status_code=429 if self.is_quota else 500,
            is_quota=self.is_quota,
            is_transient=self.is_transient,
        )


class MockSuccessProvider(BaseLLMProvider):
    def __init__(self, name: str):
        self._name = name
        self.call_count = 0

    def provider_name(self) -> str:
        return self._name

    def supports_structured_output(self) -> bool:
        return True

    async def health_check(self) -> bool:
        return True

    async def generate_decision(
        self, prompt: str, agent_personality: str, agent_role: str, current_round: int, scenario_id: str, *args, **kwargs
    ) -> AgentDecision:
        self.call_count += 1
        return AgentDecision(
            action="counteroffer",
            message=f"Proposal from {self._name}",
            rationale_summary=f"Generated by {self._name}",
            offer={"price": "$50/user/month"},
            concession_percentage=5.0,
            confidence_score=0.95,
        )


@pytest.mark.asyncio
async def test_primary_provider_success():
    primary = MockSuccessProvider("gemini")
    fallback = FallbackRuleProvider()
    manager = LLMProviderManager(providers=[primary, fallback])

    decision = await manager.generate_decision(
        prompt="Test prompt",
        agent_personality="Analytical",
        agent_role="Vendor Sales Director",
        current_round=1,
        scenario_id="vendor-pricing",
        session_id="test-session-123",
    )

    assert isinstance(decision, AgentDecision)
    assert decision.message == "Proposal from gemini"
    assert decision.offer == {"price": "$50/user/month"}


@pytest.mark.asyncio
async def test_gemini_429_quota_immediate_failover():
    primary_quota = MockFailingProvider("gemini", is_quota=True, is_transient=False)
    groq = MockSuccessProvider("groq")
    manager = LLMProviderManager(providers=[primary_quota, groq])

    decision = await manager.generate_decision(
        prompt="Test prompt",
        agent_personality="Analytical",
        agent_role="Vendor Sales Director",
        current_round=1,
        scenario_id="vendor-pricing",
        session_id="test-session-429",
    )

    # Primary should only be attempted ONCE when quota error occurs (no retries)
    assert primary_quota.call_count == 1
    assert decision.message == "Proposal from groq"


@pytest.mark.asyncio
async def test_transient_error_retry_and_fallback():
    primary_transient = MockFailingProvider("gemini", is_quota=False, is_transient=True)
    groq = MockSuccessProvider("groq")

    with patch("app.core.config.settings.LLM_MAX_RETRIES", 1), patch("asyncio.sleep", new_callable=AsyncMock):
        manager = LLMProviderManager(providers=[primary_transient, groq])
        decision = await manager.generate_decision(
            prompt="Test prompt",
            agent_personality="Collaborative",
            agent_role="Procurement Manager",
            current_round=1,
            scenario_id="vendor-pricing",
            session_id="test-session-500",
        )

    # Primary attempted initial call + 1 retry = 2 calls total
    assert primary_transient.call_count == 2
    assert decision.message == "Proposal from groq"


@pytest.mark.asyncio
async def test_gemini_failure_groq_failure_openrouter_success():
    gemini = MockFailingProvider("gemini", is_quota=True)
    groq = MockFailingProvider("groq", is_quota=False, is_transient=True)
    openrouter = MockSuccessProvider("openrouter")
    rule_fallback = FallbackRuleProvider()

    with patch("app.core.config.settings.LLM_MAX_RETRIES", 0):
        manager = LLMProviderManager(providers=[gemini, groq, openrouter, rule_fallback])
        decision = await manager.generate_decision(
            prompt="Test prompt",
            agent_personality="Aggressive",
            agent_role="VP of Finance",
            current_round=2,
            scenario_id="budget-allocation",
            session_id="test-session-chain-3",
        )

    assert gemini.call_count == 1
    assert groq.call_count == 1
    assert openrouter.call_count == 1
    assert decision.message == "Proposal from openrouter"


@pytest.mark.asyncio
async def test_gemini_failure_groq_failure_openrouter_failure_rulefallback():
    gemini = MockFailingProvider("gemini", is_quota=True)
    groq = MockFailingProvider("groq", is_quota=True)
    openrouter = MockFailingProvider("openrouter", is_quota=True)
    rule_fallback = FallbackRuleProvider()

    manager = LLMProviderManager(providers=[gemini, groq, openrouter, rule_fallback])
    decision = await manager.generate_decision(
        prompt="Test prompt",
        agent_personality="Risk-Averse",
        agent_role="Procurement Director",
        current_round=1,
        scenario_id="vendor-pricing",
        session_id="test-session-all-fail",
    )

    assert gemini.call_count == 1
    assert groq.call_count == 1
    assert openrouter.call_count == 1
    assert isinstance(decision, AgentDecision)
    assert decision.action in ["offer", "counteroffer", "accept"]


def test_openrouter_specific_model_config():
    provider = OpenRouterProvider(api_key="test-key", model_name="google/gemma-4-31b-it:free")
    assert provider.model_name == "google/gemma-4-31b-it:free"
    assert provider.provider_name() == "openrouter"


def test_openrouter_free_router_config():
    provider = OpenRouterProvider(api_key="test-key", model_name="openrouter/free")
    assert provider.model_name == "openrouter/free"
    assert provider.provider_name() == "openrouter"


def test_provider_model_ids_read_from_config():
    with patch("app.core.config.settings.GEMINI_MODEL", "gemini-1.5-flash"), \
         patch("app.core.config.settings.GROQ_MODEL", "llama-3.3-70b-versatile"), \
         patch("app.core.config.settings.OPENROUTER_MODEL", "nvidia/nemotron-3-super:free"):

        gemini = GeminiProvider()
        groq = GroqProvider()
        openrouter = OpenRouterProvider()

        assert gemini.model_name == "gemini-1.5-flash"
        assert groq.model_name == "llama-3.3-70b-versatile"
        assert openrouter.model_name == "nvidia/nemotron-3-super:free"


def test_api_keys_read_from_environment():
    with patch("app.core.config.settings.GEMINI_API_KEY", "dummy-gemini-key"), \
         patch("app.core.config.settings.GROQ_API_KEY", "dummy-groq-key"), \
         patch("app.core.config.settings.OPENROUTER_API_KEY", "dummy-openrouter-key"):

        gemini = GeminiProvider()
        groq = GroqProvider()
        openrouter = OpenRouterProvider()

        assert gemini.api_key == "dummy-gemini-key"
        assert groq.api_key == "dummy-groq-key"
        assert openrouter.api_key == "dummy-openrouter-key"


def test_api_keys_never_appear_in_logs(caplog):
    key = "secret_key_12345_do_not_log"
    provider = GroqProvider(api_key=key, model_name="llama-3.3-70b-versatile")
    
    with caplog.at_level(logging.DEBUG):
        logger = logging.getLogger("test_logger")
        logger.info(f"Provider {provider.provider_name()} initialized with model {provider.model_name}")

    log_content = caplog.text
    assert key not in log_content
    assert "llama-3.3-70b-versatile" in log_content


@pytest.mark.asyncio
async def test_no_provider_attempted_twice_in_same_turn():
    p1 = MockFailingProvider("gemini", is_quota=True)
    p2 = MockFailingProvider("gemini", is_quota=True)  # Duplicate provider name
    p3 = MockSuccessProvider("groq")

    manager = LLMProviderManager(providers=[p1, p2, p3])
    decision = await manager.generate_decision(
        prompt="Test prompt",
        agent_personality="Collaborative",
        agent_role="Buyer",
        current_round=1,
        scenario_id="vendor-pricing",
    )

    assert p1.call_count == 1
    assert p2.call_count == 0  # Deduplicated by manager
    assert p3.call_count == 1
    assert decision.message == "Proposal from groq"


@pytest.mark.asyncio
async def test_negotiation_state_remains_unchanged_during_failover(caplog):
    primary_quota = MockFailingProvider("gemini", is_quota=True)
    groq_success = MockSuccessProvider("groq")
    manager = LLMProviderManager(providers=[primary_quota, groq_success])

    engine = LangGraphNegotiationEngine(provider_manager=manager)

    state: NegotiationState = {
        "session_id": "sess-state-preserve-test",
        "scenario_id": "vendor-pricing",
        "mode": "ai-ai",
        "current_round": 2,
        "max_rounds": 10,
        "current_speaker_index": 1,
        "current_turn_speaker": "Procurement Lead",
        "agents": [
            {
                "id": "agent-1",
                "name": "Vendor VP",
                "role": "Sales VP",
                "avatar": "VP",
                "personality": "Aggressive",
                "goals": [],
                "constraints": [],
            },
            {
                "id": "agent-2",
                "name": "Procurement Lead",
                "role": "Procurement Lead",
                "avatar": "PL",
                "personality": "Collaborative",
                "goals": [],
                "constraints": [],
            },
        ],
        "messages": [
            {"sender": "Vendor VP", "role": "Sales VP", "content": "Initial price is $70/mo", "offer_data": {"price": "$70/user/month"}}
        ],
        "current_offer": {"price": "$70/user/month"},
        "agreement_reached": False,
        "deadlock_detected": False,
        "status": "running",
        "latest_decision": None,
    }

    res = await engine.agent_reasoning_node(state)

    # State parameters preserved correctly (speaker 1 completes turn -> speaker 0 is next -> round advances to 3)
    assert res["current_round"] == 3
    assert len(res["messages"]) == 2
    assert res["messages"][1]["sender"] == "Procurement Lead"
    assert res["latest_decision"]["action"] == "counteroffer"
